services:
  postgres-db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: microtask
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mongo-db:
    image: mongo:6
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - "27016:27017"
    volumes:
      - mongo_data:/data/db
      - ./init-scripts:/docker-entrypoint-initdb.d

  service-users:
    build:
      context: ./service-users
      dockerfile: Dockerfile
    container_name: service-users
    environment:
      DATABASE_MONGO_URI: mongodb://admin:1234@mongo-db:27017/microtask?retryWrites=true&w=majority
      RMQ_URI: amqp://guest:guest@rabbitmq:5672
      DATABASE_HOST: postgres-db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 1234
      DATABASE_NAME: microtask
      NODE_ENV: local
      API_PREFIX: api/service-users/v1
      API_PORT: 3001
      API_TOKEN_KEY_VALUE: 7fd2e24a7d6a7b666588c44d4f563e0334a789bae42a56368560c983170a269e
      API_URL: http://localhost:3001
    ports:
      - "3001:3001"
    depends_on:
      - postgres-db
      - rabbitmq
      - mongo-db

  service-tasks:
    build:
      context: ./service-tasks
      dockerfile: Dockerfile
    container_name: service-tasks
    environment:
      DATABASE_MONGO_URI: mongodb://admin:1234@mongo-db:27017/microtask?retryWrites=true&w=majority
      RMQ_URI: amqp://guest:guest@rabbitmq:5672
      DATABASE_HOST: postgres-db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 1234
      DATABASE_NAME: microtask
      NODE_ENV: local
      API_PREFIX: api/service-tasks/v1
      API_PORT: 3002
      API_TOKEN_KEY_VALUE: 7fd2e24a7d6a7b666588c44d4f563e0334a789bae42a56368560c983170a269e
      API_URL: http://localhost:3002
    ports:
      - "3002:3002"
    depends_on:
      - postgres-db
      - rabbitmq
      - mongo-db

  service-teams:
    build:
      context: ./service-teams
      dockerfile: Dockerfile
    container_name: service-teams
    environment:
      DATABASE_MONGO_URI: mongodb://admin:1234@mongo-db:27017/microtask?retryWrites=true&w=majority
      RMQ_URI: amqp://guest:guest@rabbitmq:5672
      DATABASE_HOST: postgres-db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 1234
      DATABASE_NAME: microtask
      NODE_ENV: local
      API_PREFIX: api/service-teams/v1
      API_PORT: 3003
      API_TOKEN_KEY_VALUE: 7fd2e24a7d6a7b666588c44d4f563e0334a789bae42a56368560c983170a269e
      API_URL: http://localhost:3003
    ports:
      - "3003:3003"
    depends_on:
      - postgres-db
      - rabbitmq
      - mongo-db

  nginx:
    image: nginx:latest
    container_name: api-gateway
    ports:
      - "81:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - service-users
      - service-tasks
      - service-teams

volumes:
  postgres_data:
  mongo_data:
